# Generated by Django 4.2.7 on 2024-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/book'),
        ),
    ]
